function drawHyperspaceLane(name1, name2) {
  const star1 = planets.find(s => s.name === name1);
  const star2 = planets.find(s => s.name === name2);
  if (!star1 || !star2) {
    console.warn("One or both star names not found:", name1, name2);
    return;
  }
  const points = [];
  points.push(new THREE.Vector3(star1.x * 2, star1.y * 2, star1.z * 2));
  points.push(new THREE.Vector3(star2.x * 2, star2.y * 2, star2.z * 2));
  const geometry = new THREE.BufferGeometry().setFromPoints(points);
  const material = new THREE.LineBasicMaterial({
    color: 0x73620d,
    transparent: false,
    opacity: 1,
  });
  const line = new THREE.Line(geometry, material);
  scene.add(line);
}

drawHyperspaceLane("Tython", "point1");
drawHyperspaceLane("point1", "Coruscant");
drawHyperspaceLane("Coruscant", "point88");
drawHyperspaceLane("point88", "point84");
drawHyperspaceLane("point84", "Jedha");
drawHyperspaceLane("point88", "point85");
drawHyperspaceLane("point85", "point86");
drawHyperspaceLane("point86", "point87");
drawHyperspaceLane("point167", "Coruscant");
drawHyperspaceLane("point167", "point166");
drawHyperspaceLane("Dorin", "point166");
drawHyperspaceLane("Dorin", "point83");
drawHyperspaceLane("point83", "point82");
drawHyperspaceLane("Dorin", "point81");
drawHyperspaceLane("Iridonia", "point81");
drawHyperspaceLane("Iridonia", "point55");
drawHyperspaceLane("point53", "point55");
drawHyperspaceLane("point52", "point53");
drawHyperspaceLane("point52", "point50");
drawHyperspaceLane("point51", "point50");
drawHyperspaceLane("Mygeeto", "point51");
drawHyperspaceLane("Dantooine", "point50");
drawHyperspaceLane("Dantooine", "point56");
drawHyperspaceLane("point50", "point56");
drawHyperspaceLane("Dantooine", "point57");
drawHyperspaceLane("Lah'mu", "point56");
drawHyperspaceLane("Lah'mu", "point59");
drawHyperspaceLane("point58", "point59");
drawHyperspaceLane("Lah'mu", "point56");
drawHyperspaceLane("point61", "point60");
drawHyperspaceLane("Lah'mu", "point61");
drawHyperspaceLane("Lah'mu", "point60");
drawHyperspaceLane("Ord Janon", "point60");
drawHyperspaceLane("Ord Janon", "point176");
drawHyperspaceLane("point62", "point61");
drawHyperspaceLane("Aldhani", "point62");
drawHyperspaceLane("Aldhani", "point174");
drawHyperspaceLane("point175", "point174");
drawHyperspaceLane("point175", "point176");
drawHyperspaceLane("Dathomir", "point176");
drawHyperspaceLane("Dathomir", "point175");
drawHyperspaceLane("Dathomir", "point177");
drawHyperspaceLane("Bogano", "point177");
drawHyperspaceLane("Dathomir", "point178");
drawHyperspaceLane("Telos", "point178");
drawHyperspaceLane("Telos", "point179");
drawHyperspaceLane("Telos", "point180");
drawHyperspaceLane("Zeffo", "point180");
drawHyperspaceLane("Bonadan", "point180");
drawHyperspaceLane("point205", "point178");
drawHyperspaceLane("Mandalore", "point205");
drawHyperspaceLane("Mandalore", "point181");
drawHyperspaceLane("point182", "point181");
drawHyperspaceLane("point183", "point182");
drawHyperspaceLane("point184", "point182");
drawHyperspaceLane("point184", "Korriban");
drawHyperspaceLane("point184", "point185");
drawHyperspaceLane("point185", "point186");
drawHyperspaceLane("Nevarro", "point186");
drawHyperspaceLane("point187", "point186")
drawHyperspaceLane("Nevarro", "point187");
drawHyperspaceLane("Nevarro", "point188");
drawHyperspaceLane("point189", "point188");
drawHyperspaceLane("Cantonica", "point189");
drawHyperspaceLane("Nevarro", "point206");
drawHyperspaceLane("Felucia", "point206");
drawHyperspaceLane("Felucia", "point145");
drawHyperspaceLane("point146", "point145");
drawHyperspaceLane("point146", "point206");
drawHyperspaceLane("point144", "point145");
drawHyperspaceLane("point143", "point144");
drawHyperspaceLane("point109", "point143");
drawHyperspaceLane("Mon Cala", "point109");
drawHyperspaceLane("point142", "point144");
drawHyperspaceLane("point109", "point142");
drawHyperspaceLane("Mon Cala", "point190");
drawHyperspaceLane("Lothal", "point190");
drawHyperspaceLane("point152", "point190");
drawHyperspaceLane("Oba Diah", "point152");
drawHyperspaceLane("Oba Diah", "point153");
drawHyperspaceLane("point192", "point153");
drawHyperspaceLane("Kessel", "point156");
drawHyperspaceLane("Kessel", "point192");
drawHyperspaceLane("point155", "point156");
drawHyperspaceLane("point155", "point154");
drawHyperspaceLane("point157", "point155");
drawHyperspaceLane("point192", "point157");
drawHyperspaceLane("point158", "point157");
drawHyperspaceLane("Eadu", "point158");
drawHyperspaceLane("point159", "point192");
drawHyperspaceLane("Vodran", "point159");
drawHyperspaceLane("point207", "Mon Cala");
drawHyperspaceLane("point159", "Klatooine");
drawHyperspaceLane("point159", "point137");
drawHyperspaceLane("point137", "Klatooine");
drawHyperspaceLane("point138", "Klatooine");
drawHyperspaceLane("point137", "point138");
drawHyperspaceLane("point139", "point138");
drawHyperspaceLane("point140", "point138");
drawHyperspaceLane("point140", "point141");
drawHyperspaceLane("point75", "point141");
drawHyperspaceLane("point75", "point76");
drawHyperspaceLane("point74", "point75");
drawHyperspaceLane("point74", "point172");
drawHyperspaceLane("point172", "point171");
drawHyperspaceLane("Onderon", "point171");
drawHyperspaceLane("point72", "Onderon");
drawHyperspaceLane("point72", "point163");
drawHyperspaceLane("point162", "point163");
drawHyperspaceLane("point162", "point161");
drawHyperspaceLane("point165", "point162");
drawHyperspaceLane("Chandrila", "point165");
drawHyperspaceLane("Chandrila", "Coruscant");
drawHyperspaceLane("point2", "Coruscant");
drawHyperspaceLane("point3", "point2");
drawHyperspaceLane("Alderaan", "point3");
drawHyperspaceLane("Chandrila", "point168");
drawHyperspaceLane("Alderaan", "point168");
drawHyperspaceLane("Alderaan", "point4");
drawHyperspaceLane("Alderaan", "point5");
drawHyperspaceLane("point7", "point5");
drawHyperspaceLane("point7", "point6");
drawHyperspaceLane("point6", "point4");
drawHyperspaceLane("point8", "point4");
drawHyperspaceLane("point9", "point8");
drawHyperspaceLane("point9", "point203");
drawHyperspaceLane("Cato Neimoidia", "point9");
drawHyperspaceLane("Cato Neimoidia", "point129");
drawHyperspaceLane("point10", "point9");
drawHyperspaceLane("point10", "Manaan");
drawHyperspaceLane("point11", "Manaan");
drawHyperspaceLane("point12", "Manaan");
drawHyperspaceLane("point11", "point13");
drawHyperspaceLane("point12", "point13");
drawHyperspaceLane("point130", "point129");
drawHyperspaceLane("point131", "point129");
drawHyperspaceLane("point130", "point131");
drawHyperspaceLane("point132", "point131");
drawHyperspaceLane("Kashyyk", "point13");
drawHyperspaceLane("Kashyyk", "point14");
drawHyperspaceLane("point204", "point14");
drawHyperspaceLane("Toydaria", "point14");
drawHyperspaceLane("Toydaria", "point18");
drawHyperspaceLane("Nal Hutta", "point18");
drawHyperspaceLane("Nal Hutta", "Toydaria");
drawHyperspaceLane("Nal Hutta", "Teth");
drawHyperspaceLane("point18", "point191");
drawHyperspaceLane("Nal Hutta", "point20");
drawHyperspaceLane("point20", "point108");
drawHyperspaceLane("point108", "point107");
drawHyperspaceLane("Kuat", "point6");
drawHyperspaceLane("point18", "point137");
drawHyperspaceLane("Glee Anselm", "Dorin");
drawHyperspaceLane("point80", "Glee Anselm");
drawHyperspaceLane("point80", "point79");
drawHyperspaceLane("Ord Mantell", "point80");
drawHyperspaceLane("Ord Mantell", "Glee Anselm");
drawHyperspaceLane("Ord Mantell", "Numidian Prime");
drawHyperspaceLane("Numidian Prime", "point79");
drawHyperspaceLane("Numidian Prime", "point78");
drawHyperspaceLane("point53", "point54");
drawHyperspaceLane("Mantooine", "point54");
drawHyperspaceLane("Mantooine", "point65");
drawHyperspaceLane("point64", "point65");
drawHyperspaceLane("point64", "point63");
drawHyperspaceLane("point77", "point64");
drawHyperspaceLane("point77", "point65");
drawHyperspaceLane("point66", "point77");
drawHyperspaceLane("point67", "point66");
drawHyperspaceLane("point68", "point67");
drawHyperspaceLane("point68", "point69");
drawHyperspaceLane("Aldhani", "point69");
drawHyperspaceLane("Taris", "point67");
drawHyperspaceLane("Taris", "point173");
drawHyperspaceLane("point173", "point205");
drawHyperspaceLane("Taris", "point70");
drawHyperspaceLane("point70", "Yavin");
drawHyperspaceLane("Taris", "point164");
drawHyperspaceLane("point71", "point164");
drawHyperspaceLane("point164", "point163");
drawHyperspaceLane("Chandrila", "point169");
drawHyperspaceLane("point170", "point169");
drawHyperspaceLane("Onderon", "point170");
drawHyperspaceLane("point73", "point172");
drawHyperspaceLane("Kijimi", "point73");
drawHyperspaceLane("Kijimi", "point187");
drawHyperspaceLane("point148", "point187");
drawHyperspaceLane("point148", "point73");
drawHyperspaceLane("point19", "point20");
drawHyperspaceLane("point19", "point17");
drawHyperspaceLane("point17", "point16");
drawHyperspaceLane("Bothawui", "point16");
drawHyperspaceLane("Bothawui", "point133");
drawHyperspaceLane("Bothawui", "point134");
drawHyperspaceLane("Bothawui", "point15");
drawHyperspaceLane("point15", "Mimban");
drawHyperspaceLane("point12", "Mimban");
drawHyperspaceLane("point6", "point21");
drawHyperspaceLane("Kuat", "point21");
drawHyperspaceLane("point7", "Corellia");
drawHyperspaceLane("point23", "Corellia");
drawHyperspaceLane("point23", "Hosnian Prime");
drawHyperspaceLane("point128", "Hosnian Prime");
drawHyperspaceLane("point128", "point127");
drawHyperspaceLane("point126", "point127");
drawHyperspaceLane("point22", "Corellia");
drawHyperspaceLane("point24", "point22");
drawHyperspaceLane("point24", "point25");
drawHyperspaceLane("point24", "point26");
drawHyperspaceLane("point27", "point25");
drawHyperspaceLane("point27", "Vandor");
drawHyperspaceLane("point28", "point27");
drawHyperspaceLane("point29", "point28");
drawHyperspaceLane("point30", "point29");
drawHyperspaceLane("point30", "point26");
drawHyperspaceLane("point30", "point48");
drawHyperspaceLane("point31", "point27");
drawHyperspaceLane("point32", "point31");
drawHyperspaceLane("point33", "point32");
drawHyperspaceLane("point33", "Savareen");
drawHyperspaceLane("point33", "Naboo");
drawHyperspaceLane("Savareen", "point38");
drawHyperspaceLane("point38", "point39");
drawHyperspaceLane("Ryloth", "point39");
drawHyperspaceLane("Ryloth", "point45");
drawHyperspaceLane("Ryloth", "point40");
drawHyperspaceLane("point41", "point40");
drawHyperspaceLane("point44", "point41");
drawHyperspaceLane("Geonosis", "point40");
drawHyperspaceLane("point24", "point25");
drawHyperspaceLane("Tatooine", "Geonosis");
drawHyperspaceLane("point33", "Tatooine");
drawHyperspaceLane("point34", "point33");
drawHyperspaceLane("Rodia", "point34");
drawHyperspaceLane("Rishi", "Rodia");
drawHyperspaceLane("Rishi", "Kamino");
drawHyperspaceLane("Rodia", "point42");
drawHyperspaceLane("Rishi", "point42");
drawHyperspaceLane("Scarif", "Rishi");
drawHyperspaceLane("point35", "point34");
drawHyperspaceLane("point36", "point35");
drawHyperspaceLane("point35", "Scarif");
drawHyperspaceLane("point36", "Scarif");
drawHyperspaceLane("Korriban", "Malachor");
drawHyperspaceLane("Cantonica", "Malachor");
drawHyperspaceLane("point147", "point148");
drawHyperspaceLane("point149", "point148");
drawHyperspaceLane("point17", "point42");
drawHyperspaceLane("point36", "point37");
drawHyperspaceLane("Koboh", "point37");
drawHyperspaceLane("Koboh", "point43");
drawHyperspaceLane("Naboo", "point46");
drawHyperspaceLane("Malastare", "point46");
drawHyperspaceLane("Malastare", "point47");
drawHyperspaceLane("Malastare", "point194");
drawHyperspaceLane("D'Qar", "point194");
drawHyperspaceLane("D'Qar", "point193");
drawHyperspaceLane("Seswenna", "point193");
drawHyperspaceLane("Seswenna", "point102");
drawHyperspaceLane("Seswenna", "point106");
drawHyperspaceLane("point105", "point106");
drawHyperspaceLane("point135", "point102");
drawHyperspaceLane("point103", "point102");
drawHyperspaceLane("point104", "point103");
drawHyperspaceLane("point194", "point195");
drawHyperspaceLane("Crait", "point195");
drawHyperspaceLane("D'Qar", "Crait");
drawHyperspaceLane("Crait", "point198");
drawHyperspaceLane("point198", "point199");
drawHyperspaceLane("point49", "point199");
drawHyperspaceLane("point30", "point49");
drawHyperspaceLane("point198", "point202");
drawHyperspaceLane("point198", "point197");
drawHyperspaceLane("point201", "point202");
drawHyperspaceLane("Eriadu", "point201");
drawHyperspaceLane("Eriadu", "Dagobah");
drawHyperspaceLane("Utapau", "Dagobah");
drawHyperspaceLane("point115", "Utapau");
drawHyperspaceLane("point116", "Utapau");
drawHyperspaceLane("Dagobah", "point100");
drawHyperspaceLane("point100", "point101");
drawHyperspaceLane("Eriadu", "point117");
drawHyperspaceLane("Mustafar", "point117");
drawHyperspaceLane("Mustafar", "Terminus");
drawHyperspaceLane("point119", "Terminus");
drawHyperspaceLane("point119", "point99");
drawHyperspaceLane("point99", "point98");
drawHyperspaceLane("Dosuun", "point98");
drawHyperspaceLane("point97", "point99");
drawHyperspaceLane("point118", "point119");
drawHyperspaceLane("point118", "Hoth");
drawHyperspaceLane("Bespin", "Hoth");
drawHyperspaceLane("point92", "point93");
drawHyperspaceLane("Bespin", "point93");
drawHyperspaceLane("point92", "point94");
drawHyperspaceLane("Takodana", "point94");
drawHyperspaceLane("Fondor", "point91");
drawHyperspaceLane("Kafrene", "point91");
drawHyperspaceLane("Fondor", "point90");
drawHyperspaceLane("Thyferra", "point90");
drawHyperspaceLane("Fondor", "Narkina");
drawHyperspaceLane("Takodana", "Narkina");
drawHyperspaceLane("Thyferra", "point89");
drawHyperspaceLane("Abregado", "point89");
drawHyperspaceLane("Jakku", "point196");
drawHyperspaceLane("Narkina", "point196");
drawHyperspaceLane("point146", "point150");
drawHyperspaceLane("point149", "point150");
drawHyperspaceLane("point151", "point150");
drawHyperspaceLane("point151", "Oba Diah");
drawHyperspaceLane("Fondor", "point208");
drawHyperspaceLane("point114", "Endor");
drawHyperspaceLane("point113", "Endor");
drawHyperspaceLane("point112", "Endor");
drawHyperspaceLane("point113", "point112");
drawHyperspaceLane("Batuu", "point112");
drawHyperspaceLane("Batuu", "Takodana");
drawHyperspaceLane("point110", "point111");
drawHyperspaceLane("Batuu", "point111");
drawHyperspaceLane("point110", "Morlana");
drawHyperspaceLane("point95", "Morlana");
drawHyperspaceLane("point96", "Morlana");
drawHyperspaceLane("Bespin", "point96");
drawHyperspaceLane("Bespin", "point95");
drawHyperspaceLane("Eriadu", "point200");
drawHyperspaceLane("Sullust", "point200");
drawHyperspaceLane("Sullust", "point120");
drawHyperspaceLane("point121", "point120");
drawHyperspaceLane("point121", "point122");
drawHyperspaceLane("point123", "point122");
drawHyperspaceLane("Thyferra", "point123");
drawHyperspaceLane("Kafrene", "point123");
drawHyperspaceLane("point123", "point125");
drawHyperspaceLane("point124", "point125");
drawHyperspaceLane("point92", "point91");
drawHyperspaceLane("point126", "point125");
drawHyperspaceLane("point128", "point125");
drawHyperspaceLane("Mortis", "point209");
drawHyperspaceLane("point57", "point209");
drawHyperspaceLane("Exegol", "point210");
drawHyperspaceLane("point211", "point210");
drawHyperspaceLane("point211", "Csilla");
drawHyperspaceLane("point212", "Csilla");
drawHyperspaceLane("point213", "Ilum");
drawHyperspaceLane("point212", "Ilum");
drawHyperspaceLane("point213", "point214");
drawHyperspaceLane("point213", "Mygeeto");
drawHyperspaceLane("point216", "point215");
drawHyperspaceLane("Csilla", "point215");
drawHyperspaceLane("point218", "Rakata");
drawHyperspaceLane("point219", "Rakata");
drawHyperspaceLane("point216", "Rakata");
drawHyperspaceLane("point114", "point217");
drawHyperspaceLane("Ahch-To", "point217");
drawHyperspaceLane("point218", "Jakku");
drawHyperspaceLane("point219", "Ahch-To");