let planetColor = 0x0061ff
let hyperspacePointColor = 0xFFC0CB

let planets = [
  { name: "Abregado", type: "planet", x: -23.5, y: 1, z: 4.4, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point89"] },
  { name: "Ahch-To", type: "planet", x: -43.5, y: 1, z: 12.5, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point217", "point219"] },
  { name: "Alderaan", type: "planet", x: -17, y: 1, z: -4.5, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point3", "point4", "point5", "point168"] },
  { name: "Aldhani", type: "planet", x: -8.85, y: 1, z: -27.2, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point62", "point69", "point174"] },
  { name: "Batuu", type: "planet", x: -32, y: 1, z: 19.6, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point111", "point112", "Takodana"] },
  { name: "Bespin", type: "planet", x: -24, y: 1, z: 24.5, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point93", "point95", "point96", "Hoth"] },
  { name: "Bogano", type: "planet", x: 0.35, y: 1, z: -32.7, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point177"] },
  { name: "Bonadan", type: "planet", x: 9.3, y: 1, z: -28.8, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point180"] },
  { name: "Bothawui", type: "planet", x: 6, y: 1, z: 5.5, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point133", "point134", "point15", "point16"] },
  { name: "Cantonica", type: "planet", x: 16, y: 1, z: -24.6, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["Malachor", "point189"] },
  { name: "Cato Neimoidia", type: "planet", x: -8.5, y: 1, z: -2.85, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point9", "point129"] },
  { name: "Chandrila", type: "planet", x: -20.25, y: 1, z: -8, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["Coruscant", "point165", "point168", "point169"] },
  { name: "Corellia", type: "planet", x: -15.25, y: 1, z: 1, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point7", "point22", "point23"] },
  { name: "Coruscant", type: "planet", x: -24, y: 1, z: -6, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point1", "point2", "Chandrila", "point88", "point167"] },
  { name: "Crait", type: "planet", x: -8.6, y: 1, z: 20.2, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point195", "point198", "D'Qar"] },
  { name: "Csilla", type: "planet", x: -48, y: 1, z: -11, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point211", "point212", "point215"] },
  { name: "Dagobah", type: "planet", x: -11.7, y: 1, z: 30, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["Eriadu", "Utapau", "point100"] },
  { name: "Dantooine", type: "planet", x: -21.8, y: 1, z: -28.6, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point57", "point56", "point50"] },
  { name: "Dathomir", type: "planet", x: -2.6, y: 1, z: -29, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point175", "point176", "point177", "point178"] },
  { name: "Dorin", type: "planet", x: -27.6, y: 1, z: -11.7, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point166", "point83", "point81", "Glee Anselm"] },
  { name: "Dosuun", type: "planet", x: -31, y: 1, z: 33, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point98"] },
  { name: "D'Qar", type: "planet", x: -5.5, y: 1, z: 22.3, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point193", "point194", "Crait"] },
  { name: "Eadu", type: "planet", x: 26.7, y: 1, z: -3.2, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point158"] },
  { name: "Endor", type: "planet", x: -34.5, y: 1, z: 13.5, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point112", "point113", "point114"] },
  { name: "Eriadu", type: "planet", x: -12.7, y: 1, z: 27.2, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point200", "point201", "Dagobah", "point117"] },
  { name: "Exegol", type: "planet", x: -50.8, y: 1, z: -21, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point210"] },
  { name: "Felucia", type: "planet", x: 13.6, y: 1, z: -18, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point145", "point206"] },
  { name: "Fondor", type: "planet", x: -25.5, y: 1, z: 11.7, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point90", "point91", "point208", "Narkina"] },
  { name: "Geonosis", type: "planet", x: 13.4, y: 1, z: 18, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point40", "Tatooine"] },
  { name: "Glee Anselm", type: "planet", x: -24.6, y: 1, z: -13.7, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["Dorin", "Ord Mantell", "point80"] },
  { name: "Hosnian Prime", type: "planet", x: -16.25, y: 1, z: 4.8, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point128", "point23"] },
  { name: "Hoth", type: "planet", x: -24.75, y: 1, z: 26, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["Bespin", "point118"] },
  { name: "Ilum", type: "planet", x: -37.5, y: 1, z: -17.8, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point212", "point213"] },
  { name: "Iridonia", type: "planet", x: -26.6, y: 1, z: -17.7, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point55", "point81"] },
  { name: "Jakku", type: "planet", x: -34.5, y: 1, z: 8, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point196", "point218"] },
  { name: "Jedha", type: "planet", x: -35.5, y: 1, z: -5.7, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point84"] },
  { name: "Kafrene", type: "planet", x: -19.5, y: 1, z: 13.5, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["Rishi"] },
  { name: "Kashyyk", type: "planet", x: 7, y: 1, z: -1.25, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point91", "point123"] },
  { name: "Kamino", type: "planet", x: 15.2, y: 1, z: 9, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point13", "point14"] },
  { name: "Kessel", type: "planet", x: 22.5, y: 1, z: -8.5, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point156", "point192"] },
  { name: "Kijimi", type: "planet", x: 5.25, y: 1, z: -14.6, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point73", "point187"] },
  { name: "Klatooine", type: "planet", x: 15, y: 1, z: -8.2, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point137", "point138", "point159"] },
  { name: "Koboh", type: "planet", x: 20, y: 1, z: 15.7, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point37", "point43"] },
  { name: "Korriban", type: "planet", x: 7, y: 1, z: -23.5, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point184", "Malachor"] },
  { name: "Kuat", type: "planet", x: -12.8, y: 1, z: -1, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point6", "point21"] },
  { name: "Lah'mu", type: "planet", x: -15, y: 1, z: -30.6, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point56", "point60", "point61", "point59"] },
  { name: "Lothal", type: "planet", x: 23, y: 1, z: -16.5, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point190"] },
  { name: "Malachor", type: "planet", x: 10.6, y: 1, z: -24.6, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["Korriban", "Cantonica"] },
  { name: "Malastare", type: "planet", x: -3, y: 1, z: 17, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point46", "point47", "point194"] },
  { name: "Manaan", type: "planet", x: -2.5, y: 1, z: -2, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point10", "point11", "point12"] },
  { name: "Mandalore", type: "planet", x: 1.85, y: 1, z: -24.7, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point205", "point181"] },
  { name: "Mantooine", type: "planet", x: -16.25, y: 1, z: -21.8, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point54", "point65"] },
  { name: "Mimban", type: "planet", x: 1.2, y: 1, z: 1.8, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point12", "point15"] },
  { name: "Mon Cala", type: "planet", x: 19.5, y: 1, z: -18.25, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point109", "point190", "point207"] },
  { name: "Morlana", type: "planet", x: -28.4, y: 1, z: 22.8, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point209"] },
  { name: "Mortis", type: "planet", x: -24.7, y: 1, z: -34.3, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point95", "point96", "point110"] },
  { name: "Mustafar", type: "planet", x: -21, y: 1, z: 30, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point117", "Terminus"] },
  { name: "Mygeeto", type: "planet", x: -26.2, y: 1, z: -24.6, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point51", "point213"] },
  { name: "Naboo", type: "planet", x: 2.2, y: 1, z: 17, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point33", "point46"] },
  { name: "Narkina", type: "planet", x: -28.8, y: 1, z: 13, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["Teth", "Toydaria", "point18", "point20"] },
  { name: "Nal Hutta", type: "planet", x: 18, y: 1, z: 1, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["Fondor", "Takodana", "point196"] },
  { name: "Nevarro", type: "planet", x: 10.3, y: 1, z: -20.5, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point186", "point187", "point188", "point206"] },
  { name: "Numidian Prime", type: "planet", x: -16, y: 1, z: -16.8, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point78", "point79", "Ord Mantell"] },
  { name: "Oba Diah", type: "planet", x: 19, y: 1, z: -13, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point151", "point152", "point153"] },
  { name: "Onderon", type: "planet", x: -7, y: 1, z: -10.6, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point170", "point171", "point72"] },
  { name: "Ord Janon", type: "planet", x: -8.3, y: 1, z: -32.2, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point60", "point176"] },
  { name: "Ord Mantell", type: "planet", x: -20.8, y: 1, z: -15.5, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["Glee Anselm", "Numidian Prime", "point80"] },
  { name: "Rakata", type: "planet", x: -43, y: 1, z: 4.5, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point216", "point218", "point219"] },
  { name: "Rishi", type: "planet", x: 13.7, y: 1, z: 11, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["Kamino", "Scarif", "Rodia", "point42"] },
  { name: "Rodia", type: "planet", x: 9.5, y: 1, z: 12, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["Rishi", "point34", "point42"] },
  { name: "Ryloth", type: "planet", x: 14.9, y: 1, z: 22.5, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point39", "point40", "point45"] },
  { name: "Savareen", type: "planet", x: 6.3, y: 1, z: 18.25, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point38", "point33"] },
  { name: "Scarif", type: "planet", x: 16, y: 1, z: 13.5, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point35", "point36", "Rishi"] },
  { name: "Seswenna", type: "planet", x: 0.8, y: 1, z: 25.25, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point106", "point102", "point193"] },
  { name: "Sullust", type: "planet", x: -14, y: 1, z: 21.5, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point120", "point200"] },
  { name: "Takodana", type: "planet", x: -27.8, y: 1, z: 16.8, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point94", "Narkina", "Batuu"] },
  { name: "Taris", type: "planet", x: -6, y: 1, z: -22, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point67", "point164", "point70", "point173"] },
  { name: "Tatooine", type: "planet", x: 10.7, y: 1, z: 16.8, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["Geonosis", "point33"] },
  { name: "Telos", type: "planet", x: 3.5, y: 1, z: -28, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point178", "point179", "point180"] },
  { name: "Terminus", type: "planet", x: -24.7, y: 1, z: 33, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["Mustafar", "point119"] },
  { name: "Teth", type: "planet", x: 22.3, y: 1, z: 0, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["Nal Hutta"] },
  { name: "Thyferra", type: "planet", x: -19.7, y: 1, z: 9.7, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point89", "point90", "point123"] },
  { name: "Toydaria", type: "planet", x: 13, y: 1, z: -0.25, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point14", "point18", "Nal Hutta"] },
  { name: "Tython", type: "planet", x: -25.25, y: 1, z: -3, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point1"] },
  { name: "Utapau", type: "planet", x: -11.7, y: 1, z: 33, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point115", "point116", "Dagobah"] },
  { name: "Vandor", type: "planet", x: -2.2, y: 1, z: 8, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point27"] },
  { name: "Vodran", type: "planet", x: 17.8, y: 1, z: -10.5, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point159"] },
  { name: "Yavin", type: "planet", x: 0, y: 1, z: -20, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point70"] },
  { name: "Zeffo", type: "planet", x: 8, y: 1, z: -30.7, color: planetColor, holocron1: false, holocron2: false, holocron3: false, textureIndex: 0, shipsAtLocation: [], occupier: "neutral", movesFromLocation: ["point180"] },
  { name: "point1", type: "point", x: -24.3, y: 1, z: -4.5, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Tython", "Coruscant"] },
  { name: "point2", type: "point", x: -21.3, y: 1, z: -5.8, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point3", "Coruscant"] },
  { name: "point3", type: "point", x: -19.3, y: 1, z: -5.25, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Alderaan", "point2"] },
  { name: "point4", type: "point", x: -15.3, y: 1, z: -3.7, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point8", "Alderaan"] },
  { name: "point5", type: "point", x: -15.8, y: 1, z: -2.9, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point7", "Alderaan"] },
  { name: "point6", type: "point", x: -14, y: 1, z: -1.2, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Kuat", "point21", "point4", "point7"] },
  { name: "point7", type: "point", x: -15, y: 1, z: -1.4, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point5", "point6", "Corellia"] },
  { name: "point8", type: "point", x: -12.2, y: 1, z: -2.7, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point4", "point9"] },
  { name: "point9", type: "point", x: -9.5, y: 1, z: -1.4, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point8", "point10", "point203", "Cato Nemoidia"] },
  { name: "point10", type: "point", x: -6.3, y: 1, z: -1.5, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point9", "Manaan"] },
  { name: "point11", type: "point", x: 0.6, y: 1, z: -3.1, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Manaan", "point13"] },
  { name: "point12", type: "point", x: -0.6, y: 1, z: -0.4, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Mimban", "Manaan", "point13"] },
  { name: "point13", type: "point", x: 3.9, y: 1, z: -2, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Kashyyk", "point11", "point12"] },
  { name: "point14", type: "point", x: 10, y: 1, z: 0.2, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Toydaria", "Kashyyk", "point204"] },
  { name: "point15", type: "point", x: 3.5, y: 1, z: 3.5, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Mimban", "Bothawui"] },
  { name: "point16", type: "point", x: 9, y: 1, z: 6.7, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point17", "Bothawui"] },
  { name: "point17", type: "point", x: 12.5, y: 1, z: 7.3, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point42", "point19", "point16"] },
  { name: "point18", type: "point", x: 17, y: 1, z: -1.8, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point137", "point191", "Nal Hutta", "Toydaria"] },
  { name: "point19", type: "point", x: 15.1, y: 1, z: 6, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point20", "point17"] },
  { name: "point20", type: "point", x: 17.4, y: 1, z: 4.5, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point19", "point108", "Nal Hutta"] },
  { name: "point21", type: "point", x: -12.5, y: 1, z: 2.1, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Kuat", "point6"] },
  { name: "point22", type: "point", x: -13.7, y: 1, z: 2.5, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Corellia", "point24"] },
  { name: "point23", type: "point", x: -15.3, y: 1, z: 2.7, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Corellia", "Hosnian Prime"] },
  { name: "point24", type: "point", x: -11.6, y: 1, z: 5, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point22", "point25", "point26"] },
  { name: "point25", type: "point", x: -7.8, y: 1, z: 7.4, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point24", "point27"] },
  { name: "point26", type: "point", x: -11.5, y: 1, z: 8, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point24", "point30"] },
  { name: "point27", type: "point", x: -4.7, y: 1, z: 9.4, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point25", "point28", "point31", "Vandor"] },
  { name: "point28", type: "point", x: -7.3, y: 1, z: 9.3, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point27", "point29"] },
  { name: "point29", type: "point", x: -9, y: 1, z: 9.7, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point28", "point30"]  },
  { name: "point30", type: "point", x: -10.6, y: 1, z: 11.1, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point26", "point29", "point48", "point49"] },
  { name: "point31", type: "point", x: -0.8, y: 1, z: 11, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point32", "point27"] },
  { name: "point32", type: "point", x: 3.3, y: 1, z: 13, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point31", "point33"] },
  { name: "point33", type: "point", x: 5.4, y: 1, z: 15.2, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point32", "point34", "Naboo", "Savareen", "Tatooine"] },
  { name: "point34", type: "point", x: 8.6, y: 1, z: 14.4, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point33", "point35", "Rodia"] },
  { name: "point35", type: "point", x: 11.8, y: 1, z: 14.5, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point34", "point36", "Scarif"] },
  { name: "point36", type: "point", x: 15, y: 1, z: 15.4, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point35", "point37", "Scarif"] },
  { name: "point37", type: "point", x: 17.6, y: 1, z: 16.7, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point36", "Koboh"] },
  { name: "point38", type: "point", x: 8.5, y: 1, z: 19.3, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point39", "Savareen"] },
  { name: "point39", type: "point", x: 11.1, y: 1, z: 20.2, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Ryloth", "point38"] },
  { name: "point40", type: "point", x: 15.3, y: 1, z: 19.4, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Geonosis", "Ryloth", "point41"] },
  { name: "point41", type: "point", x: 16.6, y: 1, z: 19.4, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point40", "point44"] },
  { name: "point42", type: "point", x: 11.6, y: 1, z: 9.5, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Rishi", "Rodia", "point17"] },
  { name: "point43", type: "point", x: 20.9, y: 1, z: 16.4, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Koboh"] },
  { name: "point44", type: "point", x: 19, y: 1, z: 20.5, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point41"] },
  { name: "point45", type: "point", x: 16., y: 1, z: 24.5, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Ryloth"] },
  { name: "point46", type: "point", x: -0.6, y: 1, z: 17.5, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Naboo", "Malastare"] },
  { name: "point47", type: "point", x: -2.1, y: 1, z: 18.2, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Malastare"] },
  { name: "point48", type: "point", x: -9.3, y: 1, z: 12.5, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point30"] },
  { name: "point49", type: "point", x: -11.2, y: 1, z: 14.3, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point30", "point199"] },
  { name: "point50", type: "point", x: -21.51, y: 1, z: -26.26, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point51", "point52", "point56", "Dantooine"] },
  { name: "point51", type: "point", x: -23.41, y: 1, z: -25.02, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point50", "Mygeeto"] },
  { name: "point52", type: "point", x: -20.70, y: 1, z: -23.92, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point50", "point53"] },
  { name: "point53", type: "point", x: -21.21, y: 1, z: -21.65, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point52", "point54", "point55"] },
  { name: "point54", type: "point", x: -19.17, y: 1, z: -20.63, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Mantooine", "point53"] },
  { name: "point55", type: "point", x: -23.33, y: 1, z: -19.09, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point53", "Iridonia"] },
  { name: "point56", type: "point", x: -18.07, y: 1, z: -28.60, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Dantooine", "Lah'mu", "point50"] },
  { name: "point57", type: "point", x: -21.36, y: 1, z: -30.94, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Dantooine", "point209"] },
  { name: "point58", type: "point", x: -17.56, y: 1, z: -31.09, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point59"] },
  { name: "point59", type: "point", x: -16.90, y: 1, z: -31.24, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Lah'mu", "point58"] },
  { name: "point60", type: "point", x: -10.83, y: 1, z: -31.31, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point61", "Ord Janon", "Lah'mu"] },
  { name: "point61", type: "point", x: -11.85, y: 1, z: -29.11, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point60", "point62", "Lah'mu"] },
  { name: "point62", type: "point", x: -10.90, y: 1, z: -27.72, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point61", "Aldhani"] },
  { name: "point63", type: "point", x: -14.56, y: 1, z: -24.43, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point64"] },
  { name: "point64", type: "point", x: -13.24, y: 1, z: -23.19, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point63", "point65", "point77"] },
  { name: "point65", type: "point", x: -13.68, y: 1, z: -21.94, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point64", "point77", "Mantooine"] },
  { name: "point66", type: "point", x: -9.66, y: 1, z: -22.02, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point67", "point77"] },
  { name: "point67", type: "point", x: -7.61, y: 1, z: -22.60, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point66", "point68", "Taris"] },
  { name: "point68", type: "point", x: -7.46, y: 1, z: -23.85, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point67", "point69"] },
  { name: "point69", type: "point", x: -8.78, y: 1, z: -25.31, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point68", "Aldhani"] },
  { name: "point70", type: "point", x: -3.22, y: 1, z: -20.12, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Yavin", "Taris"] },
  { name: "point71", type: "point", x: -6.14, y: 1, z: -17.99, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point164"] },
  { name: "point72", type: "point", x: -8.05, y: 1, z: -13.68, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Onderon", "point163"] },
  { name: "point73", type: "point", x: 3.44, y: 1, z: -12.51, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point148", "point172", "Kijimi"] },
  { name: "point74", type: "point", x: 3.51, y: 1, z: -9.95, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point75", "point172"] },
  { name: "point75", type: "point", x: 6.95, y: 1, z: -9.00, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point74", "point76", "point141"] },
  { name: "point76", type: "point", x: 8.12, y: 1, z: -9.58, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point75"] },
  { name: "point77", type: "point", x: -11.48, y: 1, z: -22.02, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point64", "point65", "point66"] },
  { name: "point78", type: "point", x: -13.46, y: 1, z: -17.04, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Numidian Prime"] },
  { name: "point79", type: "point", x: -18.36, y: 1, z: -15.14, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Numidian Prime", "point80"] },
  { name: "point80", type: "point", x: -21.43, y: 1, z: -14.04, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point79", "Glee Anselm", "Ord Mantell"] },
  { name: "point81", type: "point", x: -27.36, y: 1, z: -14.19, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Dorin", "Iridonia"] },
  { name: "point82", type: "point", x: -31.45, y: 1, z: -14.56, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point83"] },
  { name: "point83", type: "point", x: -29.85, y: 1, z: -12.51, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point82", "Dorin"] },
  { name: "point84", type: "point", x: -30.58, y: 1, z: -6.80, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point88", "Jedha"] },
  { name: "point85", type: "point", x: -29.99, y: 1, z: -5.19, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point86", "point88"] },
  { name: "point86", type: "point", x: -31.45, y: 1, z: -3.73, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point85", "point87"] },
  { name: "point87", type: "point", x: -31.97, y: 1, z: -2.19, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point86"] },
  { name: "point88", type: "point", x: -27.65, y: 1, z: -6.14, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point84", "point85", "Coruscant"] },
  { name: "point89", type: "point", x: -21.87, y: 1, z: 7.83, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Abregado", "Thyferra"] },
  { name: "point90", type: "point", x: -21.94, y: 1, z: 11.34, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Thyferra", "Fondor"] },
  { name: "point91", type: "point", x: -21.87, y: 1, z: 15.07, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Kafrene", "Fondor", "point92"] },
  { name: "point92", type: "point", x: -23.04, y: 1, z: 18.36, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point91", "point93", "point94"] },
  { name: "point93", type: "point", x: -23.92, y: 1, z: 21.29, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point92", "Bespin"] },
  { name: "point94", type: "point", x: -25.46, y: 1, z: 17.70, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point92", "Takodana"] },
  { name: "point95", type: "point", x: -25.75, y: 1, z: 22.82, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Bespin", "Morlana"] },
  { name: "point96", type: "point", x: -26.26, y: 1, z: 23.63, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Bespin", "Morlana"] },
  { name: "point97", type: "point", x: -29.55, y: 1, z: 29.70, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point99"] },
  { name: "point98", type: "point", x: -28.82, y: 1, z: 32.33, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point99", "Dosuun"] },
  { name: "point99", type: "point", x: -27.72, y: 1, z: 31.02, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point97", "point98", "point119"] },
  { name: "point100", type: "point", x: -8.92, y: 1, z: 30.14, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point101", "Dagobah"] },
  { name: "point101", type: "point", x: -7.31, y: 1, z: 28.38, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point100"] },
  { name: "point102", type: "point", x: 0.80, y: 1, z: 27.87, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point103", "point135", "Seswenna"] },
  { name: "point103", type: "point", x: 3.73, y: 1, z: 28.09, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point102", "point104"] },
  { name: "point104", type: "point", x: 6.88, y: 1, z: 27.72, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point103"] },
  { name: "point105", type: "point", x: 3.80, y: 1, z: 23.48, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point106"] },
  { name: "point106", type: "point", x: 3.00, y: 1, z: 24.94, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Seswenna", "point105"] },
  { name: "point107", type: "point", x: 21.43, y: 1, z: 5.63, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point108"] },
  { name: "point108", type: "point", x: 18.51, y: 1, z: 5.19, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point107", "point20"] },
  { name: "point109", type: "point", x: 17.63, y: 1, z: -17.19, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point142", "point143", "Mon Cala"] },
  { name: "point110", type: "point", x: -31.02, y: 1, z: 21.94, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point111", "Morlana"] },
  { name: "point111", type: "point", x: -29.99, y: 1, z: 20.99, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point110", "Batuu"] },
  { name: "point112", type: "point", x: -33.87, y: 1, z: 15.87, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Batuu", "Endor", "point113"] },
  { name: "point113", type: "point", x: -35.99, y: 1, z: 15.43, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Endor", "point112"] },
  { name: "point114", type: "point", x: -36.06, y: 1, z: 11.70, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Endor", "point217"] },
  { name: "point115", type: "point", x: -12.95, y: 1, z: 35.48, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Utapau"] },
  { name: "point116", type: "point", x: -14.56, y: 1, z: 32.62, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Utapau"] },
  { name: "point117", type: "point", x: -16.68, y: 1, z: 28.53, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Eriadu", "Mustafar"] },
  { name: "point118", type: "point", x: -25.09, y: 1, z: 26.63, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point119", "Hoth"] },
  { name: "point119", type: "point", x: -25.82, y: 1, z: 29.26, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point118", "point99", "Terminus"] },
  { name: "point120", type: "point", x: -15.36, y: 1, z: 17.92, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point121", "Sullust"] },
  { name: "point121", type: "point", x: -14.85, y: 1, z: 15.80, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point120", "point122"] },
  { name: "point122", type: "point", x: -16.39, y: 1, z: 14.26, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point121", "point123"] },
  { name: "point123", type: "point", x: -18.07, y: 1, z: 10.97, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point122", "point125", "Kafrene", "Thyferra"] },
  { name: "point124", type: "point", x: -16.53, y: 1, z: 9.66, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point125"] },
  { name: "point125", type: "point", x: -17.19, y: 1, z: 8.63, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point123", "point124", "point126", "point128"] },
  { name: "point126", type: "point", x: -15.29, y: 1, z: 8.12, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point125", "point127"] },
  { name: "point127", type: "point", x: -15.73, y: 1, z: 7.31, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point126", "point128"] },
  { name: "point128", type: "point", x: -16.53, y: 1, z: 6.58, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point125", "point127", "Hosnian Prime"] },
  { name: "point129", type: "point", x: -6.66, y: 1, z: -4.75, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point130", "point131", "Cato Neimoidia"] },
  { name: "point130", type: "point", x: -6.51, y: 1, z: -6.22, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point129", "point131"] },
  { name: "point131", type: "point", x: -4.54, y: 1, z: -5.56, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point129", "point130", "point132"] },
  { name: "point132", type: "point", x: -2.78, y: 1, z: -6.95, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point131"] },
  { name: "point133", type: "point", x: 5.93, y: 1, z: 6.80, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Bothawui"] },
  { name: "point134", type: "point", x: 4.02, y: 1, z: 6.36, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Bothawui"] },
  { name: "point135", type: "point", x: 0.29, y: 1, z: 29.48, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point102"] },
  { name: "point137", type: "point", x: 16.17, y: 1, z: -5.85, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point18", "point138", "point159", "Klatooine"] },
  { name: "point138", type: "point", x: 13.53, y: 1, z: -6.58, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point137", "point139", "point140", "Klatooine"] },
  { name: "point139", type: "point", x: 11.85, y: 1, z: -5.41, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point138"] },
  { name: "point140", type: "point", x: 11.70, y: 1, z: -8.05, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point141", "point138"] },
  { name: "point141", type: "point", x: 9.22, y: 1, z: -7.97, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point75", "point140"] },
  { name: "point142", type: "point", x: 16.46, y: 1, z: -16.53, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point109", "point144"] },
  { name: "point143", type: "point", x: 15.73, y: 1, z: -17.34, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point109", "point144"] },
  { name: "point144", type: "point", x: 14.85, y: 1, z: -16.97, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point142", "point143", "point145"] },
  { name: "point145", type: "point", x: 13.61, y: 1, z: -16.97, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point144", "point146", "Felucia"] },
  { name: "point146", type: "point", x: 12.36, y: 1, z: -17.04, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point150", "point206", "point145"] },
  { name: "point147", type: "point", x: 10.24, y: 1, z: -16.02, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point148"] },
  { name: "point148", type: "point", x: 7.39, y: 1, z: -13.90, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point73", "point147", "point149", "point187"] },
  { name: "point149", type: "point", x: 10.61, y: 1, z: -13.31, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point150", "point148"] },
  { name: "point150", type: "point", x: 13.46, y: 1, z: -14.70, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point146", "point149", "point151"] },
  { name: "point151", type: "point", x: 16.09, y: 1, z: -13.61, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point150", "Oba Diah"] },
  { name: "point152", type: "point", x: 22.09, y: 1, z: -13.53, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point190", "Oba Diah"] },
  { name: "point153", type: "point", x: 21.58, y: 1, z: -11.34, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point192", "Oba Diah"] },
  { name: "point154", type: "point", x: 25.53, y: 1, z: -8.92, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point155"] },
  { name: "point155", type: "point", x: 23.99, y: 1, z: -7.83, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point154", "point156", "point157"] },
  { name: "point156", type: "point", x: 23.55, y: 1, z: -8.49, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Kessel", "point155"] },
  { name: "point157", type: "point", x: 22.31, y: 1, z: -7.02, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point155", "point158", "point192"] },
  { name: "point158", type: "point", x: 24.58, y: 1, z: -5.49, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Eadu", "point157"] },
  { name: "point159", type: "point", x: 18.87, y: 1, z: -6.51, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Vodran", "Klatooine", "point137", "point192"] },
  { name: "point161", type: "point", x: -12.80, y: 1, z: -13.24, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point162"] },
  { name: "point162", type: "point", x: -15.22, y: 1, z: -13.39, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point161", "point163", "point165"] },
  { name: "point163", type: "point", x: -10.46, y: 1, z: -15.07, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point162", "point164", "point72"] },
  { name: "point164", type: "point", x: -7.68, y: 1, z: -18.14, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Taris", "point163", "point71"] },
  { name: "point165", type: "point", x: -19.17, y: 1, z: -10.90, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Chandrila", "point162"] },
  { name: "point166", type: "point", x: -26.48, y: 1, z: -10.31, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Dorin", "point167"] },
  { name: "point167", type: "point", x: -24.58, y: 1, z: -8.56, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point166", "Coruscant"] },
  { name: "point168", type: "point", x: -18.51, y: 1, z: -6.66, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Alderaan", "Chandrila"] },
  { name: "point169", type: "point", x: -14.34, y: 1, z: -9.36, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point170", "Chandrila"] },
  { name: "point170", type: "point", x: -10.31, y: 1, z: -10.39, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point169", "Onderon"] },
  { name: "point171", type: "point", x: -4.39, y: 1, z: -10.09, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Onderon", "point172"] },
  { name: "point172", type: "point", x: -0.73, y: 1, z: -11.34, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point73", "point74", "point171"] },
  { name: "point173", type: "point", x: -3.29, y: 1, z: -23.92, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Taris", "point205"] },
  { name: "point174", type: "point", x: -7.68, y: 1, z: -28.67, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point175", "Aldhani"] },
  { name: "point175", type: "point", x: -6.07, y: 1, z: -29.04, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Dathomir", "point174", "point176"] },
  { name: "point176", type: "point", x: -6.58, y: 1, z: -31.16, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Ord Janon", "Dathomir", "point175"] },
  { name: "point177", type: "point", x: -1.61, y: 1, z: -31.53, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Bogano", "Dathomir"] },
  { name: "point178", type: "point", x: 0.07, y: 1, z: -27.65, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Telos", "Dathomir", "point205"] },
  { name: "point179", type: "point", x: 4.61, y: 1, z: -26.85, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Telos"] },
  { name: "point180", type: "point", x: 6.95, y: 1, z: -28.89, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Zeffo", "Bonadan", "Telos"] },
  { name: "point181", type: "point", x: 3.88, y: 1, z: -23.85, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point182", "Mandalore"] },
  { name: "point182", type: "point", x: 5.12, y: 1, z: -22.68, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point181", "point183", "point184"] },
  { name: "point183", type: "point", x: 3.51, y: 1, z: -21.65, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point182"] },
  { name: "point184", type: "point", x: 6.14, y: 1, z: -22.60, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point182", "point185", "Korriban"] },
  { name: "point185", type: "point", x: 7.31, y: 1, z: -21.80, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point184", "point186"] },
  { name: "point186", type: "point", x: 8.12, y: 1, z: -21.21, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point185", "point187", "Nevarro"] },
  { name: "point187", type: "point", x: 8.12, y: 1, z: -17.99, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point148", "point186", "Nevarro", "Kijimi"] },
  { name: "point188", type: "point", x: 12.80, y: 1, z: -21.14, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point189", "Nevarro"] },
  { name: "point189", type: "point", x: 13.97, y: 1, z: -22.90, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point188", "Cantonica"] },
  { name: "point190", type: "point", x: 20.56, y: 1, z: -16.61, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point152", "Lothal", "Mon Cala"] },
  { name: "point191", type: "point", x: 19.38, y: 1, z: -1.54, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point18"] },
  { name: "point192", type: "point", x: 20.92, y: 1, z: -8.41, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point153", "point157", "point159", "Kessel"] },
  { name: "point193", type: "point", x: -2.56, y: 1, z: 23.55, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Seswenna", "D'Qar"] },
  { name: "point194", type: "point", x: -6.36, y: 1, z: 18.43, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point195", "Malastare", "D'Qar"] },
  { name: "point195", type: "point", x: -6.95, y: 1, z: 19.97, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point194", "Crait"] },
  { name: "point196", type: "point", x: -32.55, y: 1, z: 10.39, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Jakku", "Narkina"] },
  { name: "point197", type: "point", x: -12.14, y: 1, z: 17.41, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point198"] },
  { name: "point198", type: "point", x: -10.61, y: 1, z: 18.95, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point197", "point199", "Crait", "point202"] },
  { name: "point199", type: "point", x: -10.17, y: 1, z: 16.39, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point198", "point49"] },
  { name: "point200", type: "point", x: -13.53, y: 1, z: 25.02, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Eriadu", "Sullust"] },
  { name: "point201", type: "point", x: -11.41, y: 1, z: 25.38, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point202", "Eriadu"] },
  { name: "point202", type: "point", x: -11.05, y: 1, z: 22.38, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point198", "point201"] },
  { name: "point203", type: "point", x: -10.31, y: 1, z: -0.44, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point9"] },
  { name: "point204", type: "point", x: 10.17, y: 1, z: 1.76, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point14"] },
  { name: "point205", type: "point", x: -0.81, y: 1, z: -25.97, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Mandalore", "point173"] },
  { name: "point206", type: "point", x: 12.44, y: 1, z: -19.17, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Felucia", "point146", "Nevarro"] },
  { name: "point207", type: "point", x: 20.56, y: 1, z: -21.87, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Mon Cala"] },
  { name: "point208", type: "point", x: -27.94, y: 1, z: 9.80, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Fondor"] },
  { name: "point209", type: "point", x: -23.12, y: 1, z: -32.92, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point57", "Mortis"] },
  { name: "point210", type: "point", x: -50.25, y: 1, z: -17.85, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Exegol", "point211"] },
  { name: "point211", type: "point", x: -49.08, y: 1, z: -13.97, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Csilla", "point210"] },
  { name: "point212", type: "point", x: -40.96, y: 1, z: -12.00, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Ilum", "Csilla"] },
  { name: "point213", type: "point", x: -35.55, y: 1, z: -24.29, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Ilum", "Mygeeto", "point214"] },
  { name: "point214", type: "point", x: -30.28, y: 1, z: -22.82, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point213"] },
  { name: "point215", type: "point", x: -44.48, y: 1, z: -6.44, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Csilla", "point216"] },
  { name: "point216", type: "point", x: -47.25, y: 1, z: 1.68, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point215", "Rakata"] },
  { name: "point217", type: "point", x: -39.94, y: 1, z: 12.36, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["point114", "Ahch-To"] },
  { name: "point218", type: "point", x: -38.92, y: 1, z: 6.00, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Jakku", "Rakata"] },
  { name: "point219", type: "point", x: -45.86, y: 1, z: 7.83, color: hyperspacePointColor, textureIndex: 0, shipsAtLocation: [], movesFromLocation: ["Rakata", "Ahch-To"] },
];
