let planetColor = 0x0061ff
let hyperspacePointColor = 0xFFC0CB

let planets = [
  { name: "Abregado", movesFromLocation: ["point89"] },
  { name: "Ahch-To", movesFromLocation: ["point217", "point219"] },
  { name: "Alderaan", movesFromLocation: ["point3", "point4", "point5", "point168"] },
  { name: "Aldhani", movesFromLocation: ["point62", "point69", "point174"] },
  { name: "Batuu", movesFromLocation: ["point111", "point112", "Takodana"] },
  { name: "Bespin", movesFromLocation: ["point93", "point95", "point96", "Hoth"] },
  { name: "Bogano" , movesFromLocation: ["point177"] },
  { name: "Bonadan", movesFromLocation: ["point180"] },
  { name: "Bothawui", movesFromLocation: ["point133", "point134", "point15", "point16"] },
  { name: "Cantonica", movesFromLocation: ["Malachor", "point189"] },
  { name: "Cato Neimoidia" , movesFromLocation: ["point9", "point129"] },
  { name: "Chandrila", movesFromLocation: ["Coruscant", "point165", "point168", "point169"] },
  { name: "Corellia", movesFromLocation: ["point7", "point22", "point23"] },
  { name: "Coruscant", movesFromLocation: ["point1", "point2", "Chandrila", "point88", "point167"] },
  { name: "Crait", movesFromLocation: ["point195", "point198", "D'Qar"] },
  { name: "Csilla", movesFromLocation: ["point211", "point212", "point215"] },
  { name: "Dagobah", movesFromLocation: ["Eriadu", "Utapau", "point100"] },
  { name: "Dantooine", movesFromLocation: ["point57", "point56", "point50"] },
  { name: "Dathomir", movesFromLocation: ["point175", "point176", "point177", "point178"] },
  { name: "Dorin", movesFromLocation: ["point166", "point83", "point81", "Glee Anselm"] },
  { name: "Dosuun", movesFromLocation: ["point98"] },
  { name: "D'Qar", movesFromLocation: ["point193", "point194", "Crait"] },
  { name: "Eadu", movesFromLocation: ["point158"] },
  { name: "Endor" , movesFromLocation: ["point112", "point113", "point114"] },
  { name: "Eriadu" , movesFromLocation: ["point200", "point201", "Dagobah", "point117"] },
  { name: "Exegol", movesFromLocation: ["point210"] },
  { name: "Felucia", movesFromLocation: ["point145", "point206"] },
  { name: "Fondor" , movesFromLocation: ["point90", "point91", "point208", "Narkina"] },
  { name: "Geonosis", movesFromLocation: ["point40", "Tatooine"] },
  { name: "Glee Anselm", movesFromLocation: ["Dorin", "Ord Mantell", "point80"] },
  { name: "Hosnian Prime" , movesFromLocation: ["point128", "point23"] },
  { name: "Hoth", movesFromLocation: ["Bespin", "point118"] },
  { name: "Ilum", movesFromLocation: ["point212", "point213"] },
  { name: "Iridonia", movesFromLocation: ["point55", "point81"] },
  { name: "Jakku", movesFromLocation: ["point196", "point218"] },
  { name: "Jedha" , movesFromLocation: ["point84"] },
  { name: "Kafrene" , movesFromLocation: ["Rishi"] },
  { name: "Kashyyk", movesFromLocation: ["point91", "point123"] },
  { name: "Kamino", movesFromLocation: ["point13", "point14"] },
  { name: "Kessel", movesFromLocation: ["point156", "point192"] },
  { name: "Kijimi" , movesFromLocation: ["point73", "point187"] },
  { name: "Klatooine", movesFromLocation: ["point137", "point138", "point159"] },
  { name: "Koboh", movesFromLocation: ["point37", "point43"] },
  { name: "Korriban", movesFromLocation: ["point184", "Malachor"] },
  { name: "Kuat", movesFromLocation: ["point6", "point21"] },
  { name: "Lah'mu", movesFromLocation: ["point56", "point60", "point61", "point59"] },
  { name: "Lothal", movesFromLocation: ["point190"] },
  { name: "Malachor" , movesFromLocation: ["Korriban", "Cantonica"] },
  { name: "Malastare", movesFromLocation: ["point46", "point47", "point194"] },
  { name: "Manaan", movesFromLocation: ["point10", "point11", "point12"] },
  { name: "Mandalore" , movesFromLocation: ["point205", "point181"] },
  { name: "Mantooine", movesFromLocation: ["point54", "point65"] },
  { name: "Mimban", movesFromLocation: ["point12", "point15"] },
  { name: "Mon Cala", movesFromLocation: ["point109", "point190", "point207"] },
  { name: "Morlana" , movesFromLocation: ["point209"] },
  { name: "Mortis", movesFromLocation: ["point95", "point96", "point110"] },
  { name: "Mustafar", movesFromLocation: ["point117", "Terminus"] },
  { name: "Mygeeto", movesFromLocation: ["point51", "point213"] },
  { name: "Naboo", movesFromLocation: ["point33", "point46"] },
  { name: "Narkina", movesFromLocation: ["Teth", "Toydaria", "point18", "point20"] },
  { name: "Nal Hutta", movesFromLocation: ["Fondor", "Takodana", "point196"] },
  { name: "Nevarro" , movesFromLocation: ["point186", "point187", "point188", "point206"] },
  { name: "Numidian Prime", movesFromLocation: ["point78", "point79", "Ord Mantell"] },
  { name: "Oba Diah", movesFromLocation: ["point151", "point152", "point153"] },
  { name: "Onderon", movesFromLocation: ["point170", "point171", "point72"] },
  { name: "Ord Janon" , movesFromLocation: ["point60", "point176"] },
  { name: "Ord Mantell", movesFromLocation: ["Glee Anselm", "Numidian Prime", "point80"] },
  { name: "Rakata", movesFromLocation: ["point216", "point218", "point219"] },
  { name: "Rishi", movesFromLocation: ["Kamino", "Scarif", "Rodia", "point42"] },
  { name: "Rodia", movesFromLocation: ["Rishi", "point34", "point42"] },
  { name: "Ryloth", movesFromLocation: ["point39", "point40", "point45"] },
  { name: "Savareen", movesFromLocation: ["point38", "point33"] },
  { name: "Scarif", movesFromLocation: ["point35", "point36", "Rishi"] },
  { name: "Seswenna", movesFromLocation: ["point106", "point102", "point193"] },
  { name: "Sullust", movesFromLocation: ["point120", "point200"] },
  { name: "Takodana" , movesFromLocation: ["point94", "Narkina", "Batuu"] },
  { name: "Taris", movesFromLocation: ["point67", "point164", "point70", "point173"] },
  { name: "Tatooine", movesFromLocation: ["Geonosis", "point33"] },
  { name: "Telos", movesFromLocation: ["point178", "point179", "point180"] },
  { name: "Terminus", movesFromLocation: ["Mustafar", "point119"] },
  { name: "Teth", movesFromLocation: ["Nal Hutta"] },
  { name: "Thyferra", movesFromLocation: ["point89", "point90", "point123"] },
  { name: "Toydaria", movesFromLocation: ["point14", "point18", "Nal Hutta"] },
  { name: "Tython", movesFromLocation: ["point1"] },
  { name: "Utapau", movesFromLocation: ["point115", "point116", "Dagobah"] },
  { name: "Vandor", movesFromLocation: ["point27"] },
  { name: "Vodran" , movesFromLocation: ["point159"] },
  { name: "Yavin", movesFromLocation: ["point70"] },
  { name: "Zeffo", movesFromLocation: ["point180"] },
  { name: "point1", movesFromLocation: ["Tython", "Coruscant"] },
  { name: "point2", movesFromLocation: ["point3", "Coruscant"] },
  { name: "point3", movesFromLocation: ["Alderaan", "point2"] },
  { name: "point4", movesFromLocation: ["point8", "Alderaan"] },
  { name: "point5", movesFromLocation: ["point7", "Alderaan"] },
  { name: "point6", movesFromLocation: ["Kuat", "point21", "point4", "point7"] },
  { name: "point7", movesFromLocation: ["point5", "point6", "Corellia"] },
  { name: "point8", movesFromLocation: ["point4", "point9"] },
  { name: "point9" , movesFromLocation: ["point8", "point10", "point203", "Cato Nemoidia"] },
  { name: "point10" , movesFromLocation: ["point9", "Manaan"] },
  { name: "point11", movesFromLocation: ["Manaan", "point13"] },
  { name: "point12", movesFromLocation: ["Mimban", "Manaan", "point13"] },
  { name: "point13", movesFromLocation: ["Kashyyk", "point11", "point12"] },
  { name: "point14", movesFromLocation: ["Toydaria", "Kashyyk", "point204"] },
  { name: "point15", movesFromLocation: ["Mimban", "Bothawui"] },
  { name: "point16", movesFromLocation: ["point17", "Bothawui"] },
  { name: "point17", movesFromLocation: ["point42", "point19", "point16"] },
  { name: "point18", movesFromLocation: ["point137", "point191", "Nal Hutta", "Toydaria"] },
  { name: "point19", movesFromLocation: ["point20", "point17"] },
  { name: "point20", movesFromLocation: ["point19", "point108", "Nal Hutta"] },
  { name: "point21", movesFromLocation: ["Kuat", "point6"] },
  { name: "point22", movesFromLocation: ["Corellia", "point24"] },
  { name: "point23", movesFromLocation: ["Corellia", "Hosnian Prime"] },
  { name: "point24",movesFromLocation: ["point22", "point25", "point26"] },
  { name: "point25", movesFromLocation: ["point24", "point27"] },
  { name: "point26",movesFromLocation: ["point24", "point30"] },
  { name: "point27", movesFromLocation: ["point25", "point28", "point31", "Vandor"] },
  { name: "point28", movesFromLocation: ["point27", "point29"] },
  { name: "point29", movesFromLocation: ["point28", "point30"]  },
  { name: "point30", movesFromLocation: ["point26", "point29", "point48", "point49"] },
  { name: "point31", movesFromLocation: ["point32", "point27"] },
  { name: "point32", movesFromLocation: ["point31", "point33"] },
  { name: "point33", movesFromLocation: ["point32", "point34", "Naboo", "Savareen", "Tatooine"] },
  { name: "point34", movesFromLocation: ["point33", "point35", "Rodia"] },
  { name: "point35", movesFromLocation: ["point34", "point36", "Scarif"] },
  { name: "point36", movesFromLocation: ["point35", "point37", "Scarif"] },
  { name: "point37", movesFromLocation: ["point36", "Koboh"] },
  { name: "point38", movesFromLocation: ["point39", "Savareen"] },
  { name: "point39", movesFromLocation: ["Ryloth", "point38"] },
  { name: "point40", movesFromLocation: ["Geonosis", "Ryloth", "point41"] },
  { name: "point41", movesFromLocation: ["point40", "point44"] },
  { name: "point42", movesFromLocation: ["Rishi", "Rodia", "point17"] },
  { name: "point43", movesFromLocation: ["Koboh"] },
  { name: "point44", movesFromLocation: ["point41"] },
  { name: "point45", movesFromLocation: ["Ryloth"] },
  { name: "point46", movesFromLocation: ["Naboo", "Malastare"] },
  { name: "point47", movesFromLocation: ["Malastare"] },
  { name: "point48", movesFromLocation: ["point30"] },
  { name: "point49", movesFromLocation: ["point30", "point199"] },
  { name: "point50", movesFromLocation: ["point51", "point52", "point56", "Dantooine"] },
  { name: "point51", movesFromLocation: ["point50", "Mygeeto"] },
  { name: "point52", movesFromLocation: ["point50", "point53"] },
  { name: "point53", movesFromLocation: ["point52", "point54", "point55"] },
  { name: "point54", movesFromLocation: ["Mantooine", "point53"] },
  { name: "point55", movesFromLocation: ["point53", "Iridonia"] },
  { name: "point56", movesFromLocation: ["Dantooine", "Lah'mu", "point50"] },
  { name: "point57", movesFromLocation: ["Dantooine", "point209"] },
  { name: "point58", movesFromLocation: ["point59"] },
  { name: "point59", movesFromLocation: ["Lah'mu", "point58"] },
  { name: "point60", movesFromLocation: ["point61", "Ord Janon", "Lah'mu"] },
  { name: "point61", movesFromLocation: ["point60", "point62", "Lah'mu"] },
  { name: "point62", movesFromLocation: ["point61", "Aldhani"] },
  { name: "point63", movesFromLocation: ["point64"] },
  { name: "point64", movesFromLocation: ["point63", "point65", "point77"] },
  { name: "point65", movesFromLocation: ["point64", "point77", "Mantooine"] },
  { name: "point66", movesFromLocation: ["point67", "point77"] },
  { name: "point67", movesFromLocation: ["point66", "point68", "Taris"] },
  { name: "point68", movesFromLocation: ["point67", "point69"] },
  { name: "point69", movesFromLocation: ["point68", "Aldhani"] },
  { name: "point70", movesFromLocation: ["Yavin", "Taris"] },
  { name: "point71", movesFromLocation: ["point164"] },
  { name: "point72", movesFromLocation: ["Onderon", "point163"] },
  { name: "point73", movesFromLocation: ["point148", "point172", "Kijimi"] },
  { name: "point74", movesFromLocation: ["point75", "point172"] },
  { name: "point75", movesFromLocation: ["point74", "point76", "point141"] },
  { name: "point76", movesFromLocation: ["point75"] },
  { name: "point77", movesFromLocation: ["point64", "point65", "point66"] },
  { name: "point78", movesFromLocation: ["Numidian Prime"] },
  { name: "point79", movesFromLocation: ["Numidian Prime", "point80"] },
  { name: "point80", movesFromLocation: ["point79", "Glee Anselm", "Ord Mantell"] },
  { name: "point81", movesFromLocation: ["Dorin", "Iridonia"] },
  { name: "point82", movesFromLocation: ["point83"] },
  { name: "point83", movesFromLocation: ["point82", "Dorin"] },
  { name: "point84", movesFromLocation: ["point88", "Jedha"] },
  { name: "point85", movesFromLocation: ["point86", "point88"] },
  { name: "point86", movesFromLocation: ["point85", "point87"] },
  { name: "point87", movesFromLocation: ["point86"] },
  { name: "point88", movesFromLocation: ["point84", "point85", "Coruscant"] },
  { name: "point89", movesFromLocation: ["Abregado", "Thyferra"] },
  { name: "point90", movesFromLocation: ["Thyferra", "Fondor"] },
  { name: "point91", movesFromLocation: ["Kafrene", "Fondor", "point92"] },
  { name: "point92", movesFromLocation: ["point91", "point93", "point94"] },
  { name: "point93", movesFromLocation: ["point92", "Bespin"] },
  { name: "point94", movesFromLocation: ["point92", "Takodana"] },
  { name: "point95", movesFromLocation: ["Bespin", "Morlana"] },
  { name: "point96", movesFromLocation: ["Bespin", "Morlana"] },
  { name: "point97", movesFromLocation: ["point99"] },
  { name: "point98", movesFromLocation: ["point99", "Dosuun"] },
  { name: "point99", movesFromLocation: ["point97", "point98", "point119"] },
  { name: "point100", movesFromLocation: ["point101", "Dagobah"] },
  { name: "point101", movesFromLocation: ["point100"] },
  { name: "point102", movesFromLocation: ["point103", "point135", "Seswenna"] },
  { name: "point103", movesFromLocation: ["point102", "point104"] },
  { name: "point104", movesFromLocation: ["point103"] },
  { name: "point105", movesFromLocation: ["point106"] },
  { name: "point106", movesFromLocation: ["Seswenna", "point105"] },
  { name: "point107", movesFromLocation: ["point108"] },
  { name: "point108", movesFromLocation: ["point107", "point20"] },
  { name: "point109", movesFromLocation: ["point142", "point143", "Mon Cala"] },
  { name: "point110", movesFromLocation: ["point111", "Morlana"] },
  { name: "point111", movesFromLocation: ["point110", "Batuu"] },
  { name: "point112", movesFromLocation: ["Batuu", "Endor", "point113"] },
  { name: "point113", movesFromLocation: ["Endor", "point112"] },
  { name: "point114", movesFromLocation: ["Endor", "point217"] },
  { name: "point115", movesFromLocation: ["Utapau"] },
  { name: "point116", movesFromLocation: ["Utapau"] },
  { name: "point117", movesFromLocation: ["Eriadu", "Mustafar"] },
  { name: "point118", movesFromLocation: ["point119", "Hoth"] },
  { name: "point119", movesFromLocation: ["point118", "point99", "Terminus"] },
  { name: "point120", movesFromLocation: ["point121", "Sullust"] },
  { name: "point121", movesFromLocation: ["point120", "point122"] },
  { name: "point122", movesFromLocation: ["point121", "point123"] },
  { name: "point123", movesFromLocation: ["point122", "point125", "Kafrene", "Thyferra"] },
  { name: "point124", movesFromLocation: ["point125"] },
  { name: "point125", movesFromLocation: ["point123", "point124", "point126", "point128"] },
  { name: "point126", movesFromLocation: ["point125", "point127"] },
  { name: "point127", movesFromLocation: ["point126", "point128"] },
  { name: "point128", movesFromLocation: ["point125", "point127", "Hosnian Prime"] },
  { name: "point129", movesFromLocation: ["point130", "point131", "Cato Neimoidia"] },
  { name: "point130", movesFromLocation: ["point129", "point131"] },
  { name: "point131", movesFromLocation: ["point129", "point130", "point132"] },
  { name: "point132", movesFromLocation: ["point131"] },
  { name: "point133", movesFromLocation: ["Bothawui"] },
  { name: "point134", movesFromLocation: ["Bothawui"] },
  { name: "point135", movesFromLocation: ["point102"] },
  { name: "point137", movesFromLocation: ["point18", "point138", "point159", "Klatooine"] },
  { name: "point138", movesFromLocation: ["point137", "point139", "point140", "Klatooine"] },
  { name: "point139", movesFromLocation: ["point138"] },
  { name: "point140", movesFromLocation: ["point141", "point138"] },
  { name: "point141", movesFromLocation: ["point75", "point140"] },
  { name: "point142", movesFromLocation: ["point109", "point144"] },
  { name: "point143", movesFromLocation: ["point109", "point144"] },
  { name: "point144", movesFromLocation: ["point142", "point143", "point145"] },
  { name: "point145", movesFromLocation: ["point144", "point146", "Felucia"] },
  { name: "point146", movesFromLocation: ["point150", "point206", "point145"] },
  { name: "point147", movesFromLocation: ["point148"] },
  { name: "point148", movesFromLocation: ["point73", "point147", "point149", "point187"] },
  { name: "point149", movesFromLocation: ["point150", "point148"] },
  { name: "point150", movesFromLocation: ["point146", "point149", "point151"] },
  { name: "point151", movesFromLocation: ["point150", "Oba Diah"] },
  { name: "point152", movesFromLocation: ["point190", "Oba Diah"] },
  { name: "point153", movesFromLocation: ["point192", "Oba Diah"] },
  { name: "point154", movesFromLocation: ["point155"] },
  { name: "point155", movesFromLocation: ["point154", "point156", "point157"] },
  { name: "point156", movesFromLocation: ["Kessel", "point155"] },
  { name: "point157", movesFromLocation: ["point155", "point158", "point192"] },
  { name: "point158", movesFromLocation: ["Eadu", "point157"] },
  { name: "point159", movesFromLocation: ["Vodran", "Klatooine", "point137", "point192"] },
  { name: "point161", movesFromLocation: ["point162"] },
  { name: "point162", movesFromLocation: ["point161", "point163", "point165"] },
  { name: "point163", movesFromLocation: ["point162", "point164", "point72"] },
  { name: "point164", movesFromLocation: ["Taris", "point163", "point71"] },
  { name: "point165", movesFromLocation: ["Chandrila", "point162"] },
  { name: "point166", movesFromLocation: ["Dorin", "point167"] },
  { name: "point167", movesFromLocation: ["point166", "Coruscant"] },
  { name: "point168", movesFromLocation: ["Alderaan", "Chandrila"] },
  { name: "point169", movesFromLocation: ["point170", "Chandrila"] },
  { name: "point170", movesFromLocation: ["point169", "Onderon"] },
  { name: "point171", movesFromLocation: ["Onderon", "point172"] },
  { name: "point172", movesFromLocation: ["point73", "point74", "point171"] },
  { name: "point173", movesFromLocation: ["Taris", "point205"] },
  { name: "point174", movesFromLocation: ["point175", "Aldhani"] },
  { name: "point175", movesFromLocation: ["Dathomir", "point174", "point176"] },
  { name: "point176", movesFromLocation: ["Ord Janon", "Dathomir", "point175"] },
  { name: "point177", movesFromLocation: ["Bogano", "Dathomir"] },
  { name: "point178", movesFromLocation: ["Telos", "Dathomir", "point205"] },
  { name: "point179", movesFromLocation: ["Telos"] },
  { name: "point180", movesFromLocation: ["Zeffo", "Bonadan", "Telos"] },
  { name: "point181", movesFromLocation: ["point182", "Mandalore"] },
  { name: "point182", movesFromLocation: ["point181", "point183", "point184"] },
  { name: "point183", movesFromLocation: ["point182"] },
  { name: "point184", movesFromLocation: ["point182", "point185", "Korriban"] },
  { name: "point185", movesFromLocation: ["point184", "point186"] },
  { name: "point186", movesFromLocation: ["point185", "point187", "Nevarro"] },
  { name: "point187", movesFromLocation: ["point148", "point186", "Nevarro", "Kijimi"] },
  { name: "point188", movesFromLocation: ["point189", "Nevarro"] },
  { name: "point189", movesFromLocation: ["point188", "Cantonica"] },
  { name: "point190", movesFromLocation: ["point152", "Lothal", "Mon Cala"] },
  { name: "point191", movesFromLocation: ["point18"] },
  { name: "point192", movesFromLocation: ["point153", "point157", "point159", "Kessel"] },
  { name: "point193", movesFromLocation: ["Seswenna", "D'Qar"] },
  { name: "point194", movesFromLocation: ["point195", "Malastare", "D'Qar"] },
  { name: "point195", movesFromLocation: ["point194", "Crait"] },
  { name: "point196", movesFromLocation: ["Jakku", "Narkina"] },
  { name: "point197", movesFromLocation: ["point198"] },
  { name: "point198", movesFromLocation: ["point197", "point199", "Crait", "point202"] },
  { name: "point199", movesFromLocation: ["point198", "point49"] },
  { name: "point200", movesFromLocation: ["Eriadu", "Sullust"] },
  { name: "point201", movesFromLocation: ["point202", "Eriadu"] },
  { name: "point202", movesFromLocation: ["point198", "point201"] },
  { name: "point203", movesFromLocation: ["point9"] },
  { name: "point204", movesFromLocation: ["point14"] },
  { name: "point205", movesFromLocation: ["Mandalore", "point173"] },
  { name: "point206", movesFromLocation: ["Felucia", "point146", "Nevarro"] },
  { name: "point207", movesFromLocation: ["Mon Cala"] },
  { name: "point208", movesFromLocation: ["Fondor"] },
  { name: "point209", movesFromLocation: ["point57", "Mortis"] },
  { name: "point210", movesFromLocation: ["Exegol", "point211"] },
  { name: "point211", movesFromLocation: ["Csilla", "point210"] },
  { name: "point212", movesFromLocation: ["Ilum", "Csilla"] },
  { name: "point213", movesFromLocation: ["Ilum", "Mygeeto", "point214"] },
  { name: "point214", movesFromLocation: ["point213"] },
  { name: "point215", movesFromLocation: ["Csilla", "point216"] },
  { name: "point216", movesFromLocation: ["point215", "Rakata"] },
  { name: "point217", movesFromLocation: ["point114", "Ahch-To"] },
  { name: "point218", movesFromLocation: ["Jakku", "Rakata"] },
  { name: "point219", movesFromLocation: ["Rakata", "Ahch-To"] },
];
